{
 "title": "PM2 Prometheus Exporter",
 "description": "Seamless PM2 Metrics monitoring: Export to Prometheus, collect with the Quickstat npm package.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   { "name": "name", "label": "PM2 App Name", "query": { "query": "label_values(name)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "PM2 App List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PM2 List",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(pm2_status_total{name=~\"$name\", application=~\"$application\"}) without(__name__,application,instance,job)"
    },
    {
     "expr": "sum(pm2_unstable_restarts_total{name=~\"$name\", application=~\"$application\"}) without(__name__,application,instance,job, name, pid)"
    },
    {
     "expr": "sum(pm2_uptime_total{name=~\"$name\", application=~\"$application\"}) without(__name__,application,instance,job, name, pid)"
    },
    {
     "expr": "sum(pm2_cpu_usage_total{name=~\"$name\", application=~\"$application\"}) without(__name__,application,instance,job, name, pid)"
    },
    {
     "expr": "sum(pm2_memory_rss_total{name=~\"$name\", application=~\"$application\"}) without(__name__,application,instance,job, name, pid)"
    },
    {
     "expr": "sum(pm2_heap_size_used_total{name=~\"$name\", application=~\"$application\"}) without(__name__,application,instance,job, name, pid)"
    },
    {
     "expr": "sum(pm2_heap_usage_total{name=~\"$name\", application=~\"$application\"}) without(__name__,application,instance,job, name, pid)"
    },
    {
     "expr": "sum(pm2_heap_size_total{name=~\"$name\", application=~\"$application\"}) without(__name__,application,instance,job, name, pid)"
    },
    {
     "expr": "sum(pm2_event_loop_latency_total{name=~\"$name\", application=~\"$application\"}) without(__name__,application,instance,job, name, pid)"
    },
    {
     "expr": "sum(pm2_active_handles_total{name=~\"$name\", application=~\"$application\"}) without(__name__,application,instance,job, name, pid)"
    },
    {
     "expr": "sum(pm2_active_requests_total{name=~\"$name\", application=~\"$application\"}) without(__name__,application,instance,job, name, pid)"
    },
    {
     "expr": "sum(pm2_http_requests_total{name=~\"$name\", application=~\"$application\"}*60000) without(__name__,application,instance,job, name, pid)"
    },
    {
     "expr": "sum(pm2_http_latency_mean_total{name=~\"$name\", application=~\"$application\"}) without(__name__,application,instance,job, name, pid)"
    }
   ]
  },
  { "title": "PM2 Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "App Uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "pm2_uptime_total{application=~\"$application\", name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "App Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pm2_memory_rss_total{application=~\"$application\", name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "App Heap Used/Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pm2_heap_size_used_total{application=~\"$application\", name=~\"$name\"}",
     "legendFormat": "Used - {{name}}"
    },
    {
     "expr": "pm2_heap_size_total{application=~\"$application\", name=~\"$name\"}",
     "legendFormat": "Total - {{name}}"
    }
   ]
  },
  {
   "title": "App CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pm2_cpu_usage_total{application=~\"$application\", name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "App Restarts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pm2_restart_time_total{application=~\"$application\", name=~\"$name\"}",
     "legendFormat": "Stable - {{name}}"
    },
    {
     "expr": "pm2_unstable_restarts_total{application=~\"$application\", name=~\"$name\"}",
     "legendFormat": "Unstable - {{name}}"
    }
   ]
  },
  {
   "title": "App Event Loop Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pm2_event_loop_latency_total{application=~\"$application\", name=~\"$name\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "pm2_event_loop_latency_p95_total{application=~\"$application\", name=~\"$name\"}",
     "legendFormat": "p95 - {{name}}"
    }
   ]
  },
  {
   "title": "App HTTP Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pm2_http_latency_mean_total{application=~\"$application\", name=~\"$name\"}",
     "legendFormat": "Mean - {{name}}"
    },
    {
     "expr": "pm2_http_latency_p95_total{application=~\"$application\", name=~\"$name\"}",
     "legendFormat": "p95 - {{name}}"
    }
   ]
  },
  {
   "title": "App Active Handles & Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pm2_active_handles_total{application=~\"$application\", name=~\"$name\"}",
     "legendFormat": "Handles - {{name}}"
    },
    {
     "expr": "pm2_active_requests_total{application=~\"$application\", name=~\"$name\"}",
     "legendFormat": "Requests - {{name}}"
    }
   ]
  },
  {
   "title": "App HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "pm2_http_requests_total{application=~\"$application\", name=~\"$name\"}*60000",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}